nairobilug/nairobilug.or.ke

- pelicanconf.py
- sitemap.py
Add sitemap.py to auto-generate sitemap.xml. Fix for issue #93. All thanks to urbanslug
> Add sitemap.py for the generation of sitemaps.

- content/meetup-february-2015.md
- content/meetup-november-2013.md
Tags are singular, like labels. Categories are plural, like buckets you put stuff in.
> content: Deduplicate tags

- requirements.txt
Update it to be more current for new clones and new virtualenvs.
> requirements.txt: Simplify package versions

- content/meetup-may-2015.md
Add post for the meetup on 2nd May 2015
Signed-off-by: Jason Rogena <jasonrogena@gmail.com>
> add post for May 2015 meetup

- content/brck-violating-gpl.md
Think before merging this. We should have a discussion whether this is appropriate for posting on the LUG blog. I don't mind attaching these allegations to my own blog / name, but I can't speak for the LUG as a whole.
Can we get some +1's and -1's here in the comments?
> Add blog post about BRCK's GPL violation

- content/meetup-july-2015.md
I added a summary for the meetup help on 04 July 2015. Please review it and merge it
> Add a summary for the LUG meetup held on 04 July 2015

- content/meetup-october-2015.md
Would be good if someone had a picture I could include from Tunapanda!
> Add blog post for October, 2015 meetup

- content/heka-influxdb-and-grafana.md
Add real dashes (U+2014) instead of this typewriter double dash nonsense! Also, use Unicode HAIR SPACE (U+200a) around dashes.
For more on dashes, see: http://practicaltypography.com/hyphens-and-dashes.html
Conceived when I almost spit my coffee out in #142.
> content/heka-influxdb-and-grafana.md: Add real dashes

- content/postgres-homebrew-macosx.md
Also posted on my blog, re-posted for posterity: https://mjanja.ch/2016/04/using-homebrews-postgresql-mac-os-x/
> Add blog post about PostgreSQL on Mac OS X

- content/applying-for-a-strange-loop-2016-opportunity-grant.md
This has been updated with regards to what was discussed here https://github.com/nairobilug/nairobilug.or.ke/pull/147
> New post: applying for a strange loop 2016 opportunity grant.

- .gitignore
- Makefile
- develop_server.sh
- scripts/requirements.txt
Update to new pelican Makefile and requirements.txt file.
We get new commands such as `make devserver` `make github` and so forth try it out 😸.
fixes #150
> Updated to new Makefile.

- content/safely-rotating-mysql-slow-logs.md
This post is also available on my personal blog; https://oguya.ch/posts/2016-04-13-safely-rotating-mysql-slow-logs/
> Add blog post about rotating MySQL slow query logs

- .gitignore
- .gitmodules
Minor changes, but can't bring myself to push to master:
- Remove cruft from .gitignore
- Less tabs -> More spaces
> Update .gitignore / .gitmodules

- content/pages/mailing-list.md
A bit opinionated, feel free to tweak.
Depends on ~~#157~~, #160
> Add mailing list page, guidelines, subscribing links, etc

- content/pages/contact.md
> Add contact page, note mailing list, irc, social media

- README.md
- A bit more concise
- Proper titlecase'd headings (not title headings)
- Screenshot reference; .png -> .jpg
- #167
> Update the repo README

- content/redirecting-http-traffic-while-using-aws-target-groups.md
Add a blogpost on using HSTS with amazon AWS target groups.
Attribution: 
@eebrah 
@jasonrogena
> Crosspost HSTS blogpost from onaio

- pelicanconf.py
It's 2017 and the Internet isn't safe!
> pelicanconf.py: Use HTTPS for GitHub and Twitter links

- requirements.txt
This is a minor release, no major changes.
See: http://docs.getpelican.com/en/stable/changelog.html
> requirements.txt: Bump Pelican 3.7.0→3.7.1

- content/hosting-kenya.md
Add some information about hosting providers in Kenya
> Hosting kenya

- content/deploying-janus-gateway.md
> How to deploy Janus on Fedora

- .github/workflows/updatewebsite.yml
- content/cache-maven-artifacts-with-artifactory.md
- content/docker-lab.md
- content/exploring-anti-dos-tools-apache-httpd.md
- content/extras/CNAME
- content/hacking-on-eudyptula-challenge.md
- content/heka-influxdb-and-grafana.md
- content/image-compression-open-source.md
- content/letsencrypt-systemd-timers.md
- content/meetup-august-2014.md
- content/meetup-december-2016.md
- content/meetup-february-2014.md
- content/meetup-january-2014.md
- content/meetup-march-2014.md
- content/meetup-november-2013.md
- content/pages/about-us.md
- content/pages/meetups.md
- content/ramping-up-ethiopia-lug.md
- content/systemd-mount-partition.md
- publishconf.py
- requirements.txt
Resolves https://github.com/nairobilug/nairobilug.or.ke/issues/186
> Update dependencies and partially migrate to nairobi.lug.or.ke
